MSMS finished with /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_4.pdb
Computing scores for  1j5plig_196.pdb
MSMS running for /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_196.pdb
MSMS finished with /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_119.pdb
Computing scores for  1j5plig_13.pdb
MSMS finished with /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_93.pdb
Computing scores for  1j5plig_51.pdb
MSMS running for /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_51.pdb
MSMS running for /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_13.pdb
MSMS finished with /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_67.pdb
Computing scores for  1j5plig_1j5prec.pdb
MSMS running for /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_1j5prec.pdb
ERROR: find_first_rs_face_external: atoms 411 and 2640 have identical centers 
Computing scores for  1j5plig_43.pdb
...
Traceback (most recent call last):
  File "meetdock", line 164, in <module>
    run_meetdock(mypath=mypath, myoutdir=myoutdir, ligChain="A", recChain="B", shape = shape, electro = electro, jones =jones, proba =proba, pH =pH, dist =dist, depth =depth, thread=thread)
  File "meetdock", line 145, in run_meetdock
    tm.tm_score(mydf, outdir = myoutdir, execdir = execdir)
  File "/home/pyxis/Documents/2017-2018_Equipe1/lib/tm_score.py", line 238, in tm_score
    score_prepared = num_pipeline.fit_transform(score_num)
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/pipeline.py", line 281, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/pipeline.py", line 213, in _fit
    **fit_params_steps[name])
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/externals/joblib/memory.py", line 362, in __call__
    return self.func(*args, **kwargs)
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/pipeline.py", line 581, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/base.py", line 517, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/preprocessing/imputation.py", line 155, in fit
MSMS running for /home/pyxis/Documents/2017-2018_Equipe1/out/sampling/1j5plig_43.pdb
    force_all_finite=False)
  File "/home/pyxis/miniconda3/envs/meetu/lib/python3.5/site-packages/sklearn/utils/validation.py", line 470, in check_array
    context))
ValueError: Found array with 0 feature(s) (shape=(4, 0)) while a minimum of 1 is required.

